# Generated by Django 4.1.2 on 2023-01-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactus',
            new_name='contact',
        ),
    ]
