# Generated by Django 4.1.2 on 2023-01-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_contactus_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=255)),
                ('CNIC', models.CharField(max_length=255)),
                ('DOB', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Height', models.CharField(max_length=255)),
                ('Bloodgroup', models.CharField(max_length=255)),
            ],
        ),
    ]
