# Generated by Django 4.1.2 on 2023-03-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='userdata',
            name='CNIC',
            field=models.IntegerField(null=True),
        ),
    ]
