# Generated by Django 4.1.2 on 2023-04-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_challan'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='user_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
