# Generated by Django 4.1.2 on 2023-04-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fee',
        ),
    ]
