# Generated by Django 4.1.2 on 2023-04-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Fullname',
        ),
    ]
