# Generated by Django 4.1.2 on 2023-05-01 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_has_submitted_registration_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challan',
            old_name='profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='profile',
            new_name='user',
        ),
    ]
