# Generated by Django 4.1.2 on 2023-05-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_profile_challan_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challan',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='user',
            new_name='profile',
        ),
    ]
