# Generated by Django 4.1.2 on 2023-05-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_user_challan_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Fullname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userdata',
            name='Fullname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
