# Generated by Django 4.1.2 on 2023-05-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_userdata_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_submitted_Challan',
            field=models.BooleanField(default=False),
        ),
    ]
