# Generated by Django 4.1.2 on 2023-05-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_profile_has_submitted_challan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='height',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
