# Generated by Django 4.1.2 on 2023-05-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_userdata_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='height',
            field=models.CharField(default='', max_length=255),
        ),
    ]
