# Generated by Django 4.1.2 on 2023-05-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_userdata_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='Fathername',
            field=models.CharField(default='', max_length=255),
        ),
    ]
