# Generated by Django 4.1.2 on 2023-05-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_userdata_fathername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='cnic',
            field=models.CharField(max_length=15),
        ),
    ]
