# Generated by Django 4.1.2 on 2023-05-08 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_userdata_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
