# Generated by Django 4.1.2 on 2023-05-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_userdata_submission_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='has_submitted_Challan',
            new_name='has_submitted_challan',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='pdf_file',
            new_name='challan_file',
        ),
        migrations.AddField(
            model_name='userdata',
            name='learner_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='pdf_files/'),
        ),
    ]
