# Generated by Django 4.1.2 on 2023-05-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_quizscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='score',
            field=models.CharField(default='', max_length=5),
        ),
    ]
