# Generated by Django 4.1.2 on 2023-05-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_video_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Learner_issue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='learner_expire',
            field=models.DateField(blank=True, null=True),
        ),
    ]
