# Generated by Django 4.1.2 on 2023-05-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_profile_learner_issue_profile_learner_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Physical_test_passed',
            field=models.BooleanField(default=False),
        ),
    ]
