# Generated by Django 4.1.2 on 2023-05-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_profile_physical_test_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
