# Generated by Django 4.1.2 on 2023-05-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_challan_rejected_video_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userdata',
            name='back_cnic_picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='cnic_pictures/'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='front_cnic_picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='cnic_pictures/'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile_pictures/'),
        ),
    ]
