# Generated by Django 4.1.2 on 2023-05-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_userdata_back_cnic_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='profile',
        ),
    ]
